/**
 * Guard for the publishing layer (see ADR-0003).
 *
 * The path allowlist is implemented for real: it is small, testable and
 * security-critical. A hijacked editor session must never be able to write
 * code or configuration, only content. The invariant covers file type too:
 * under the content prefixes only data and image extensions are allowed,
 * never anything that can execute under `script-src 'self'` (js/html and
 * the like).
 */

/** Paths publishing may NEVER write (prefix or exact match). */
const DENY_PREFIXES = ['functions/', '.github/', 'admin/', 'assets/engine/', 'assets/urd/'];
const DENY_EXACT = ['_headers', '_redirects', 'urd.json', 'index.html', '404.html', '.gitignore', 'wrangler.toml'];

/**
 * Paths publishing MAY write, with an extension allowlist per prefix.
 * In practice the editor writes only .json/.css (content/) and .webp/.svg
 * (media/); common raster formats are included as slack for media added to git
 * by hand.
 */
const ALLOW_PREFIX_EXTENSIONS = {
  'content/': ['json', 'css', 'xml'],
  // The audio and video extensions cover the audio block and the video
  // background layer (published unchanged from data URLs); none of them can
  // execute as a script.
  'media/': ['webp', 'svg', 'png', 'jpg', 'jpeg', 'gif', 'avif', 'ico',
    'mp3', 'm4a', 'aac', 'wav', 'ogg', 'flac', 'mp4', 'webm'],
};
// The visibility files (the SEO pack) are generated by publishing at the root
// level; xml/txt can never execute under script-src 'self'.
const ALLOW_EXACT = ['plugins/plugins.json', 'sitemap.xml', 'robots.txt'];

/**
 * Page routing: publishing may write `<slug>/index.html` (a copy of the root
 * index.html per page, so routing works on every static host) - but NEVER the
 * root index.html, and never under reserved folders.
 */
const PAGE_INDEX_RE = /^[a-z0-9][a-z0-9-]*\/index\.html$/;
const RESERVED_SLUGS = ['admin', 'api', 'assets', 'content', 'media', 'plugins', 'functions', 'readme'];

/** Shared normalisation: slashes, and reject absolute paths and `..`. */
function normalizePath(path) {
  if (typeof path !== 'string' || path.length === 0) return null;
  const normalized = path.replaceAll('\\', '/');
  if (normalized.startsWith('/') || normalized.split('/').includes('..')) return null;
  return normalized;
}

/**
 * @param {string} path Repo-relative file path from a commit request
 * @returns {boolean} true if the path is safe to write via publishing
 */
export function isAllowedPath(path) {
  const normalized = normalizePath(path);
  if (!normalized) return false;
  if (DENY_EXACT.includes(normalized)) return false;
  if (DENY_PREFIXES.some((p) => normalized.startsWith(p))) return false;
  if (ALLOW_EXACT.includes(normalized)) return true;
  if (PAGE_INDEX_RE.test(normalized) && !RESERVED_SLUGS.includes(normalized.split('/')[0])) return true;
  const filename = normalized.split('/').pop();
  const dot = filename.lastIndexOf('.');
  if (dot <= 0) return false; // a file without an extension (or a bare dotfile) is rejected
  const extension = filename.slice(dot + 1).toLowerCase();
  return Object.entries(ALLOW_PREFIX_EXTENSIONS).some(
    ([prefix, extensions]) => normalized.startsWith(prefix) && extensions.includes(extension)
  );
}

/**
 * The ownership map for the updater: mirrors ownedPaths/userPaths in urd.json,
 * because functions cannot read the repo's urd.json at runtime. The contract
 * test in tests/guard.test.mjs requires the lists to be identical to urd.json,
 * so they never drift. The only pattern forms are an exact path and
 * `prefix/**` - keep it that way.
 */
export const OWNED_PATTERNS = [
  'index.html',
  '404.html',
  'urd.json',
  '_headers',
  'speculation-rules.json',
  'README.md',
  'readme/**',
  'admin/**',
  'assets/engine/**',
  'assets/urd/**',
  'assets/styles/base.css',
  'functions/**',
];
export const USER_PATTERNS = ['content/**', 'media/**', 'plugins/**', 'sitemap.xml', 'robots.txt'];

/** @param {string} pattern Exact path or `prefix/**` */
export function matchesPattern(pattern, path) {
  if (pattern.endsWith('/**')) return path.startsWith(pattern.slice(0, -2));
  return path === pattern;
}

/** Urd-owned path (the updater's domain; publishing rejects all of these). */
export function isOwnedPath(path) {
  const normalized = normalizePath(path);
  return normalized !== null && OWNED_PATTERNS.some((p) => matchesPattern(p, normalized));
}

/** User-owned path (content/media/plugins; the updater never touches these). */
export function isUserPath(path) {
  const normalized = normalizePath(path);
  return normalized !== null && USER_PATTERNS.some((p) => matchesPattern(p, normalized));
}

/** Page-routing copy (`<slug>/index.html`): written by publishing, and
 *  refreshed by the updater in the same commit as an engine swap (ADR-0013). */
export function isPageIndexCopy(path) {
  const normalized = normalizePath(path);
  return normalized !== null
    && PAGE_INDEX_RE.test(normalized)
    && !RESERVED_SLUGS.includes(normalized.split('/')[0]);
}

/**
 * Checks that a GitHub username is in ALLOWED_LOGINS (a comma-separated
 * environment variable). Enforced in ALL mutating endpoints (defence in depth).
 * @param {string} login
 * @param {{ALLOWED_LOGINS?: string}} env
 */
export function isAllowedLogin(login, env) {
  const allowed = (env.ALLOWED_LOGINS || '')
    .split(',')
    .map((s) => s.trim().toLowerCase())
    .filter(Boolean);
  return allowed.includes(String(login).toLowerCase());
}
